trigger:
- master  # You can change this to the branch you want to trigger the pipeline

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'  # Change this to the Python version you're using accordingly
    addToPath: true

- script: |
    python -m pip install --upgrade pip
  displayName: 'Upgrade pip'

- script: |
    # Commands to build your application (if needed)
  displayName: 'Build application'

- script: |
    # Commands to run unit tests
    # Since you don't have a specific path, assume tests are in the root directory
    python -m unittest discover
  displayName: 'Run unit tests'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'drop'
    publishLocation: 'Container'
